katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_todolist
from todolist.views import delete_todolist
from todolist.views import update_todolist
from todolist.views import show_todolist_json
from todolist.views import add_todolist
from todolist.views import show_todolist_ajax
from todolist.views import update_todolist_ajax
from todolist.views import delete_todolist_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/',register, name='register'),
    path('login/',login_user,name='login'),
    path('logout/',logout_user,name='logout'),
    path('create-task',create_todolist,name='create_todolist'),
    path('delete-task/<int:id>',delete_todolist,name='delete_todolist'),
    path('update-task/<int:id>',update_todolist,name='update_todolist'),
    path('json/',show_todolist_json, name='show_todolist_json'),
    path('add-task/', add_todolist, name='add_todolist'),
    path('ajax/',show_todolist_ajax, name='show_todolist_ajax'),
    path('update-task-ajax/<int:id>',update_todolist_ajax,name='update_todolist_ajax'),
    path('delete-task-ajax/<int:id>',delete_todolist,name='delete_todolist_ajax'),
]

todolist/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateField(default=datetime.now())
    title = models.CharField(max_length=250)
    description = models.TextField()
    finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateTask(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'title',
            'description',
        ]
        widgets = {
            'title': forms.TextInput(attrs={
                'class' : 'form-control',
                'style' : 'border-radius: 5px',
            }),
            'description': forms.Textarea(attrs={
                'class' : 'form-control',
                'style' : 'border-radius: 5px; resize: none',
                'rows' : '7',
            })
        }

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        max_length=200,
        required = True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
    )
    password1 = forms.CharField(
        required = True,
        label = "Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
    )

    password2 = forms.CharField(
        required = True,
        label = "Confirm Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
    )

    check = forms.BooleanField(
        label = "I Agree to the Terms of Use and Privacy Policy",
        required = True)

    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]

todolist/views.py
import datetime
import json
from urllib import request
from todolist.models import Task
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from todolist.forms import CreateTask
from todolist.forms import CustomUserCreationForm
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect
from django.http import HttpResponse, HttpRequest
from django.core import serializers
from django.urls import reverse
from datetime import datetime

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist = Task.objects.filter(user=request.user)
    context = {
        'username' : request.user.username,
        'todolist' : todolist,
        'name' : 'Nadhif Rahman Alfan',
        'student_id' : '2106751783',
    }
    return render(request,"todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    todolist = Task.objects.filter(user=request.user)
    context = {
        'username' : request.user.username,
        'name' : 'Nadhif Rahman Alfan',
        'student_id' : '2106751783',
    }
    return render(request,"todolist_ajax.html", context)

@login_required(login_url='/todolist/login/')
def show_todolist_json(request):
    todolist = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", todolist), content_type="application/json")

@login_required(login_url='/todolist/login/')
def create_todolist(request):
    form = CreateTask()
    if request.method == "POST":
        form = CreateTask(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('todolist:show_todolist')
    context = {
        'form':form
    }
    return render(request,'create-task.html',context)

@login_required(login_url='/todolist/login/')
def add_todolist(request):
    if request.method == 'POST':
        new_task = Task(title=request.POST['title'], description=request.POST['description'], user=request.user)
        new_task.save()
        return HttpResponse(serializers.serialize("json", [new_task]), content_type="application/json")
    return HttpResponse()

@login_required(login_url='/todolist/login/')
def delete_todolist(request,id):
    task = Task.objects.filter(id=id)[0]
    task.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def update_todolist(request,id):
    task = Task.objects.filter(id=id)[0]
    task.finished = not task.finished
    task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def update_todolist_ajax(request,id):
    task = Task.objects.filter(id=id)[0]
    task.finished = not task.finished
    task.save()
    return redirect('todolist:show_todolist_ajax')

@login_required(login_url='/todolist/login/')
def delete_todolist_ajax(request,id):
    task = Task.objects.filter(id=id)[0]
    task.delete()
    return redirect('todolist:show_todolist_ajax')

def register(request):
    if request.method == 'GET':
        form  = CustomUserCreationForm()
        context = {'form': form}
        return render(request, 'register.html', context)
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Akun telah berhasil dibuat untuk ' + user + '!')
            return redirect('todolist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.now()))
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return redirect('todolist:login')

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Buat Task</title>
{% endblock meta %}

{% block content %}  


<div style="margin-top: 100px;margin-left: 30%;margin-right: 30%;">
<h1 style="text-align: center;">Buat Task</h1> 
    <form method="POST" class="form-control">  
        {% csrf_token %}  
        <table>  
            <tr>{{ form.as_div }}</tr>
            <tr>  
                <input style="border-radius: 5px;" class="button" type="submit" name="submit" value="Daftar"/>
                <button style="border-radius: 5px; margin-top: 10px; margin-left: 10px;"><a style="color:black; text-decoration: none;"" href="{% url 'todolist:show_todolist' %}">Kembali</a></button>
            </tr>  
        </table>  
    </form>
</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class=".bg-light.bg-gradient" style="margin-top: 100px;margin-left: 35%;margin-right: 35%;">
    <h1 style="text-align: center;">Login</h1>
    <form method="POST" action="" class="form-control">
        {% csrf_token %}
        <table>
                <tr>Username: </tr>
                <tr><input type="text" name="username" placeholder="Username" class="form-control" style="border-radius:10px"></tr>  
                <tr>Password: </tr>
                <tr><input type="password" name="password" placeholder="Password" class="form-control" style="border-radius:10px"></tr>
                <tr></tr>
                <tr><input style="border-radius: 10px;margin-top: 10px;" type="submit" value="Login" ></tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li style="color: whitesmoke;">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <p>Belum mempunyai akun? <a style="color:whitesmoke" href="{% url 'todolist:register' %}">Buat Akun</a></p>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<div class="login" style="margin-top: 100px;margin-left: 30%;margin-right: 30%;">
    <h1>Formulir Registrasi</h1>  

        <form method="POST" class="form-control">  
            {% csrf_token %}
            <table style="border-radius: 10px;">
            <tr style="border-radius: 10px;">{{ form.as_div }}  </tr>
            <tr> <input style="border-radius: 10px;margin-top: 5px;" type="submit" name="submit" value="Daftar"/>
            <button style="border-radius: 10px; margin-left: 10px;margin-top: 5px;"><a style="color: black; text-decoration: none; " href="{% url 'todolist:login' %}">Kembali</a></button></td>
        </tr>    
        </table>
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}    
<title>My Todolist</title>
<style> 
    .card {
      width: 75%;
      height: max-content;
      transition: width 1s;
    }
    
    .card:hover {
      width: 100%;
    }
    </style>
{% endblock meta %}

{% block content %}
<nav class="navbar" style="background-color: #34495e;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1" style="color: white;">To Do List by {{name}} - {{student_id}}</span>
      <div>
        <button style="border-radius: 10px; align-items:flex-end;"><a style="color: black; text-decoration: none;" href="{% url 'todolist:create_todolist' %}">Create New Task</a></button>
        <button style="border-radius: 10px; align-items:flex-end;"><a style="color: black; text-decoration: none;" href="{% url 'todolist:logout' %}">Logout</a></button>
      </div>
    </div>
  </nav>

<!-- <h3>Name: </h3>
<p>{{name}}</p>
<h3>Student ID: </h3>
<p>{{student_id}}</p> -->

<h3 style="text-align: center;margin-top: 20px;">Welcome, {{username}}!</h3>
<div>
{% for task in todolist %}
    <div class="card" style="margin-bottom: 10px; margin-left: auto; margin-right: auto;">
        <div class="card-body">
                    <table>
                            <th>
                                <tr>
                                    <h5 class="card-title">{{task.title}}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">{{task.date}}
                                    {% if task.finished %}
                                        <p1>Finished</p1>
                                        {% else %}
                                        <p1>Not Finished</p1>
                                    {% endif %}
                                    </h6>
                                </tr>
                                <tr>
                                    <textarea class="form-control" style="color: black; white-space: nowrap; text-overflow: ellipsis; resize: none;" class="card-text" disabled>{{task.description}}</textarea>
                                </tr>
                            </th>
                            <td class="align-items-center justify-content-center">
                            <a style="color: black; text-decoration: none; align-items: center;" href="{% url 'todolist:update_todolist' task.id %}" class="card-link">Update</a>
                            <a style="color: black; text-decoration: none; align-items: center;" href="{% url 'todolist:delete_todolist' task.id %}" class="card-link">Delete</a>
                            </td>
                    </table>
                </div>
    </div>
    {% endfor %}
</div>
  
{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

<head>
{% block meta %}    
<title>My Todolist</title>
<style> 
    .card {
      width: 75%;
      height: max-content;
      transition: width 1s;
    }
    
    .card:hover {
      width: 100%;
    }
    </style>
{% endblock meta %}
</head>

<body>
{% block content %}
<nav class="navbar" style="background-color: #34495e;">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1" style="color: white;">To Do List by {{name}} - {{student_id}}</span>
    <div>
      <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" style="border-radius: 10px; align-items:flex-end;">Create New Task</button>
      <button style="border-radius: 10px; align-items:flex-end;"><a style="color: black; text-decoration: none;" href="{% url 'todolist:logout' %}">Logout</a></button>
    </div>
  </div>
</nav>

<h3 style="text-align: center;margin-top: 20px;">Welcome, {{username}}!</h3>

<div id="mikum">

</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Create New Task</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" class="form-control" id="createTask">
          {% csrf_token %}
          <table style="border-radius: 10px;">
            <tr style="border-radius: 10px;">
              <input type="text" style="border-radius: 5px;" name="title" id="title" placeholder="Task Title" class="form-control">
            </tr>
            <tr style="border-radius: 10px;">
              <textarea style="border-radius: 5px; resize: none;margin-top: 10px;" name="description" id="description" placeholder="Task Description" class="form-control" rows="7"></textarea>
            </tr>
            <tr>
              <input type="submit" style="border-radius: 10px; margin-left: 10px; margin-top: 5px;color: black; text-decoration: none; align-items: center;" value="Create">
            </tr>
          </table>
        </form>
      </div>
    </div>
  </div>
</div>
  
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
  console.log("test")
  function getData(){
    $.get("{% url 'todolist:show_todolist_json'%}", function(data){
      console.log(data)
      var div = $('#mikum')
      div.empty()
      for (let i = 0; i < data.length; i++) {
        var topTag = document.createElement("div")
        var secTag = document.createElement("div")
        
        var title = document.createElement("h5")
        title.classList.add("card-title")
        title.innerHTML = data[i].fields.title
        
        var subtitle = document.createElement("h6")
        subtitle.classList.add("card-subtitle","mb-2","text-muted")
        var date = new Date(data[i].fields.date)
        subtitle.innerHTML = date.toDateString()
        
        
        var status = document.createElement("p1")
        if (data[i].fields.finished == true){
          status.innerHTML = "Finished"
        } else {
          status.innerHTML = "Not Finished"
        }
        
        subtitle.append(status)

        var description = document.createElement("textarea")
        description.disabled = true
        description.classList.add("form-control", "card-text")
        description.style = "color: black; white-space: nowrap; text-overflow: ellipsis; resize: none;"
        description.innerHTML = data[i].fields.description

        var table = document.createElement("table")
        var tr = document.createElement("tr")
        var td = document.createElement("td")
        td.classList.add("align-items-center","justify-content-center")

        var update = document.createElement("a")
        update.classList.add("card-link")
        update.style = "color: black; text-decoration: none; align-items: center;"
        update.innerHTML = "Update"
        update.href = "/todolist/update-task-ajax/" + data[i].pk

        var deleteBtn = document.createElement("a")
        deleteBtn.classList.add("card-link")
        deleteBtn.style = "color: black; text-decoration: none; align-items: center;"
        deleteBtn.innerHTML = "Delete"
        deleteBtn.href = "/todolist/delete-task-ajax/" + data[i].pk

        td.append(update)
        td.append(deleteBtn)
        tr.append(td)
        table.append(tr)

        secTag.appendChild(title)
        secTag.appendChild(subtitle)
        secTag.appendChild(description)
        secTag.appendChild(table)
        topTag.appendChild(secTag)
        secTag.classList.add("card-body")
        topTag.classList.add("card") 
        topTag.style = "margin-bottom: 10px; margin-left: auto; margin-right: auto;"
        div.append(topTag)
      }
    })
  }

  $(document).ready(function() {
    getData()

    $("#createTask").submit(function (e) {
      e.preventDefault()
      const formData = {
        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
        title: $('#title').val(),
        description: $('#description').val(),
      }
      $.ajax({
        async: true,
        type: "POST",
        url: "/todolist/add-task/",
        data: formData,
        dataType: 'json',
        success: function(response){
          $('#exampleModal').modal('toggle');
          getData()
          $("#createTask").each(function(){
            this.reset();
          })
        }
      })
    })
  })
</script>
{% endblock content %}

</body>

<!-- <div>
{% for task in todolist %}
    <div class="card" style="margin-bottom: 10px; margin-left: auto; margin-right: auto;">
        <div class="card-body">
                    <table>
                            <th>
                                <tr>
                                    <h5 class="card-title">{{task.title}}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">{{task.date}}
                                    {% if task.finished %}
                                        <p1>Finished</p1>
                                        {% else %}
                                        <p1>Not Finished</p1>
                                    {% endif %}
                                    </h6>
                                </tr>
                                <tr>
                                    <textarea class="form-control" style="color: black; white-space: nowrap; text-overflow: ellipsis; resize: none;" class="card-text" disabled>{{task.description}}</textarea>
                                </tr>
                            </th>
                            <td class="align-items-center justify-content-center">
                            <a style="color: black; text-decoration: none; align-items: center;" href="{% url 'todolist:update_todolist' task.id %}" class="card-link">Update</a>
                            <a style="color: black; text-decoration: none; align-items: center;" href="{% url 'todolist:delete_todolist' task.id %}" class="card-link">Delete</a>
                            </td>
                    </table>
                </div>
    </div>
    {% endfor %}
</div> -->